version: '3'

services:

  wordpress:
    container_name: docker_wordpress
    build:
      context: .
      args:
        WORDPRESS_UPSTREAM_VERSION: ${WORDPRESS_UPSTREAM_VERSION}
        WORDPRESS_VERSION: ${WORDPRESS_UPSTREAM_VERSION}
        WORDPRESS_BACKUP_FILENAME: ${WORDPRESS_BACKUP_FILENAME}
    restart: always
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html
    depends_on: 
      - db

  db:
    container_name: docker_wordpress_db
    image: mysql:8.0.2
    restart: always
    ports: 
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: my_secret_password
    volumes:
      - ./data/db:/var/lib/mysql:rw
  
  phpmyadmin:
    container_name: docker_wordpress_pma
    image: phpmyadmin:5.1.1
    restart: always
    ports:
      - "${PMA_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
